---
# https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml
#
default: true
gitignore: true
MD007: # ul-indent
  indent: 4
MD013: # line-length
  line_length: 300
MD033: # no-inline-html
  allowed_elements: [div, a, img]

# ignores:
#   - "docs/**.md"
