---
# https://trivy.dev/latest/docs/references/configuration/config-file/
report: "all"
exit-code: 1
insecure: false
debug: false
quiet: true
timeout: 10m
dependency-tree: true
list-all-pkgs: true
format: "table"
# output: result.json
ignorefile: ".trivyignore.yaml"

severity:
  - UNKNOWN
  - LOW
  - MEDIUM
  - HIGH
  - CRITICAL

# [EXPERIMENTAL] tables that will be displayed in 'table' format, default '[summary,detailed]'
# explicit setting breaks CI's 'github' format
# table-mode:
#   - summary
#   - detailed

scan:
  detection-priority: "precise"
  disable-telemetry: true
  offline: true
  scanners:
    - vuln
    - secret
    - misconfig
  skip-dirs: ["**/.terraform/**", "**/.terragrunt-cache/**", "openapi/**"]
  # skip-files: []

vulnerability:
  ignore-unfixed: false

misconfiguration:
  include-non-failures: false
  scanners:
    # - azure-arm
    # - cloudformation
    - dockerfile
    - helm
    - kubernetes
    - terraform
    - terraformplan-json
    - terraformplan-snapshot

  terraform:
    exclude-downloaded-modules: true

# TODO: add licensing restrictions, https://trivy.dev/latest/docs/references/configuration/config-file/#license-options
