---
# https://yamllint.readthedocs.io/en/stable/configuration.html

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamlfmt'
  - '.yamllint'

extends: default
ignore: |
  .git/
  *_cache/
  *-info/
  build/
  dist/
  node_modules/
  tmp/
  .terraform/

rules:
  braces:
    forbid: false
    min-spaces-inside: 0 # race condition with 'yamlfmt' on inline {...} definitions
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  comments:
    min-spaces-from-content: 1
  empty-values: enable
  line-length:
    max: 160
