---
# https://github.com/google/yamlfmt/blob/main/docs/config-file.md
formatter:
  type: basic
  indent: 2
  include_document_start: true
  scan_folded_as_literal: true
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
