// Copyright (c) 2022 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/indykite/indykite-sdk-go/gen/indykite/trusted_data/access/v1beta1 (interfaces: TrustedDataControlAPIClient)
//
// Generated by this command:
//
//	mockgen -copyright_file ./doc/LICENSE -package access -destination ./test/trusted_data/access/v1beta1/trusted_data_access_api_mock.go github.com/indykite/indykite-sdk-go/gen/indykite/trusted_data/access/v1beta1 TrustedDataControlAPIClient
//

// Package access is a generated GoMock package.
package access

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	accessv1beta1 "github.com/indykite/indykite-sdk-go/gen/indykite/trusted_data/access/v1beta1"
)

// MockTrustedDataControlAPIClient is a mock of TrustedDataControlAPIClient interface.
type MockTrustedDataControlAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockTrustedDataControlAPIClientMockRecorder
}

// MockTrustedDataControlAPIClientMockRecorder is the mock recorder for MockTrustedDataControlAPIClient.
type MockTrustedDataControlAPIClientMockRecorder struct {
	mock *MockTrustedDataControlAPIClient
}

// NewMockTrustedDataControlAPIClient creates a new mock instance.
func NewMockTrustedDataControlAPIClient(ctrl *gomock.Controller) *MockTrustedDataControlAPIClient {
	mock := &MockTrustedDataControlAPIClient{ctrl: ctrl}
	mock.recorder = &MockTrustedDataControlAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrustedDataControlAPIClient) EXPECT() *MockTrustedDataControlAPIClientMockRecorder {
	return m.recorder
}

// AccessConsentedData mocks base method.
func (m *MockTrustedDataControlAPIClient) AccessConsentedData(arg0 context.Context, arg1 *accessv1beta1.AccessConsentedDataRequest, arg2 ...grpc.CallOption) (*accessv1beta1.AccessConsentedDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AccessConsentedData", varargs...)
	ret0, _ := ret[0].(*accessv1beta1.AccessConsentedDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessConsentedData indicates an expected call of AccessConsentedData.
func (mr *MockTrustedDataControlAPIClientMockRecorder) AccessConsentedData(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessConsentedData", reflect.TypeOf((*MockTrustedDataControlAPIClient)(nil).AccessConsentedData), varargs...)
}

// GrantConsent mocks base method.
func (m *MockTrustedDataControlAPIClient) GrantConsent(arg0 context.Context, arg1 *accessv1beta1.GrantConsentRequest, arg2 ...grpc.CallOption) (*accessv1beta1.GrantConsentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantConsent", varargs...)
	ret0, _ := ret[0].(*accessv1beta1.GrantConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantConsent indicates an expected call of GrantConsent.
func (mr *MockTrustedDataControlAPIClientMockRecorder) GrantConsent(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantConsent", reflect.TypeOf((*MockTrustedDataControlAPIClient)(nil).GrantConsent), varargs...)
}

// RevokeConsent mocks base method.
func (m *MockTrustedDataControlAPIClient) RevokeConsent(arg0 context.Context, arg1 *accessv1beta1.RevokeConsentRequest, arg2 ...grpc.CallOption) (*accessv1beta1.RevokeConsentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeConsent", varargs...)
	ret0, _ := ret[0].(*accessv1beta1.RevokeConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeConsent indicates an expected call of RevokeConsent.
func (mr *MockTrustedDataControlAPIClientMockRecorder) RevokeConsent(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeConsent", reflect.TypeOf((*MockTrustedDataControlAPIClient)(nil).RevokeConsent), varargs...)
}
