// Copyright (c) 2022 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/indykite/indykite-sdk-go/gen/indykite/ingest/v1beta3 (interfaces: IngestAPIClient,IngestAPI_StreamRecordsClient)
//
// Generated by this command:
//
//	mockgen -copyright_file ./doc/LICENSE -package ingest -destination ./test/ingest/v1beta3/ingest_api_mock.go github.com/indykite/indykite-sdk-go/gen/indykite/ingest/v1beta3 IngestAPIClient,IngestAPI_StreamRecordsClient
//

// Package ingest is a generated GoMock package.
package ingest

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"

	ingestv1beta3 "github.com/indykite/indykite-sdk-go/gen/indykite/ingest/v1beta3"
)

// MockIngestAPIClient is a mock of IngestAPIClient interface.
type MockIngestAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIngestAPIClientMockRecorder
	isgomock struct{}
}

// MockIngestAPIClientMockRecorder is the mock recorder for MockIngestAPIClient.
type MockIngestAPIClientMockRecorder struct {
	mock *MockIngestAPIClient
}

// NewMockIngestAPIClient creates a new mock instance.
func NewMockIngestAPIClient(ctrl *gomock.Controller) *MockIngestAPIClient {
	mock := &MockIngestAPIClient{ctrl: ctrl}
	mock.recorder = &MockIngestAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestAPIClient) EXPECT() *MockIngestAPIClientMockRecorder {
	return m.recorder
}

// BatchDeleteNodeProperties mocks base method.
func (m *MockIngestAPIClient) BatchDeleteNodeProperties(ctx context.Context, in *ingestv1beta3.BatchDeleteNodePropertiesRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchDeleteNodePropertiesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteNodeProperties", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchDeleteNodePropertiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeleteNodeProperties indicates an expected call of BatchDeleteNodeProperties.
func (mr *MockIngestAPIClientMockRecorder) BatchDeleteNodeProperties(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteNodeProperties", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchDeleteNodeProperties), varargs...)
}

// BatchDeleteNodeTags mocks base method.
func (m *MockIngestAPIClient) BatchDeleteNodeTags(ctx context.Context, in *ingestv1beta3.BatchDeleteNodeTagsRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchDeleteNodeTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteNodeTags", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchDeleteNodeTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeleteNodeTags indicates an expected call of BatchDeleteNodeTags.
func (mr *MockIngestAPIClientMockRecorder) BatchDeleteNodeTags(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteNodeTags", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchDeleteNodeTags), varargs...)
}

// BatchDeleteNodes mocks base method.
func (m *MockIngestAPIClient) BatchDeleteNodes(ctx context.Context, in *ingestv1beta3.BatchDeleteNodesRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchDeleteNodesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteNodes", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchDeleteNodesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeleteNodes indicates an expected call of BatchDeleteNodes.
func (mr *MockIngestAPIClientMockRecorder) BatchDeleteNodes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteNodes", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchDeleteNodes), varargs...)
}

// BatchDeleteRelationshipProperties mocks base method.
func (m *MockIngestAPIClient) BatchDeleteRelationshipProperties(ctx context.Context, in *ingestv1beta3.BatchDeleteRelationshipPropertiesRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchDeleteRelationshipPropertiesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteRelationshipProperties", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchDeleteRelationshipPropertiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeleteRelationshipProperties indicates an expected call of BatchDeleteRelationshipProperties.
func (mr *MockIngestAPIClientMockRecorder) BatchDeleteRelationshipProperties(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteRelationshipProperties", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchDeleteRelationshipProperties), varargs...)
}

// BatchDeleteRelationships mocks base method.
func (m *MockIngestAPIClient) BatchDeleteRelationships(ctx context.Context, in *ingestv1beta3.BatchDeleteRelationshipsRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchDeleteRelationshipsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchDeleteRelationships", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchDeleteRelationshipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeleteRelationships indicates an expected call of BatchDeleteRelationships.
func (mr *MockIngestAPIClientMockRecorder) BatchDeleteRelationships(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeleteRelationships", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchDeleteRelationships), varargs...)
}

// BatchUpsertNodes mocks base method.
func (m *MockIngestAPIClient) BatchUpsertNodes(ctx context.Context, in *ingestv1beta3.BatchUpsertNodesRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchUpsertNodesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchUpsertNodes", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchUpsertNodesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpsertNodes indicates an expected call of BatchUpsertNodes.
func (mr *MockIngestAPIClientMockRecorder) BatchUpsertNodes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsertNodes", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchUpsertNodes), varargs...)
}

// BatchUpsertRelationships mocks base method.
func (m *MockIngestAPIClient) BatchUpsertRelationships(ctx context.Context, in *ingestv1beta3.BatchUpsertRelationshipsRequest, opts ...grpc.CallOption) (*ingestv1beta3.BatchUpsertRelationshipsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BatchUpsertRelationships", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.BatchUpsertRelationshipsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpsertRelationships indicates an expected call of BatchUpsertRelationships.
func (mr *MockIngestAPIClientMockRecorder) BatchUpsertRelationships(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsertRelationships", reflect.TypeOf((*MockIngestAPIClient)(nil).BatchUpsertRelationships), varargs...)
}

// IngestRecord mocks base method.
func (m *MockIngestAPIClient) IngestRecord(ctx context.Context, in *ingestv1beta3.IngestRecordRequest, opts ...grpc.CallOption) (*ingestv1beta3.IngestRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IngestRecord", varargs...)
	ret0, _ := ret[0].(*ingestv1beta3.IngestRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestRecord indicates an expected call of IngestRecord.
func (mr *MockIngestAPIClientMockRecorder) IngestRecord(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestRecord", reflect.TypeOf((*MockIngestAPIClient)(nil).IngestRecord), varargs...)
}

// StreamRecords mocks base method.
func (m *MockIngestAPIClient) StreamRecords(ctx context.Context, opts ...grpc.CallOption) (ingestv1beta3.IngestAPI_StreamRecordsClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamRecords", varargs...)
	ret0, _ := ret[0].(ingestv1beta3.IngestAPI_StreamRecordsClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamRecords indicates an expected call of StreamRecords.
func (mr *MockIngestAPIClientMockRecorder) StreamRecords(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamRecords", reflect.TypeOf((*MockIngestAPIClient)(nil).StreamRecords), varargs...)
}

// MockIngestAPI_StreamRecordsClient is a mock of IngestAPI_StreamRecordsClient interface.
type MockIngestAPI_StreamRecordsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIngestAPI_StreamRecordsClientMockRecorder
	isgomock struct{}
}

// MockIngestAPI_StreamRecordsClientMockRecorder is the mock recorder for MockIngestAPI_StreamRecordsClient.
type MockIngestAPI_StreamRecordsClientMockRecorder struct {
	mock *MockIngestAPI_StreamRecordsClient
}

// NewMockIngestAPI_StreamRecordsClient creates a new mock instance.
func NewMockIngestAPI_StreamRecordsClient(ctrl *gomock.Controller) *MockIngestAPI_StreamRecordsClient {
	mock := &MockIngestAPI_StreamRecordsClient{ctrl: ctrl}
	mock.recorder = &MockIngestAPI_StreamRecordsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngestAPI_StreamRecordsClient) EXPECT() *MockIngestAPI_StreamRecordsClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).Context))
}

// Header mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) Recv() (*ingestv1beta3.StreamRecordsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*ingestv1beta3.StreamRecordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockIngestAPI_StreamRecordsClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) Send(arg0 *ingestv1beta3.StreamRecordsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockIngestAPI_StreamRecordsClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockIngestAPI_StreamRecordsClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockIngestAPI_StreamRecordsClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockIngestAPI_StreamRecordsClient)(nil).Trailer))
}
