// Copyright (c) 2022 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/indykite/indykite-sdk-go/gen/indykite/knowledge/v1beta2 (interfaces: IdentityKnowledgeAPIClient)
//
// Generated by this command:
//
//	mockgen -copyright_file ./doc/LICENSE -package knowledge -destination ./test/knowledge/v1beta2/identity_knowledge_api_mock.go github.com/indykite/indykite-sdk-go/gen/indykite/knowledge/v1beta2 IdentityKnowledgeAPIClient
//

// Package knowledge is a generated GoMock package.
package knowledge

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	knowledgev1beta2 "github.com/indykite/indykite-sdk-go/gen/indykite/knowledge/v1beta2"
)

// MockIdentityKnowledgeAPIClient is a mock of IdentityKnowledgeAPIClient interface.
type MockIdentityKnowledgeAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityKnowledgeAPIClientMockRecorder
	isgomock struct{}
}

// MockIdentityKnowledgeAPIClientMockRecorder is the mock recorder for MockIdentityKnowledgeAPIClient.
type MockIdentityKnowledgeAPIClientMockRecorder struct {
	mock *MockIdentityKnowledgeAPIClient
}

// NewMockIdentityKnowledgeAPIClient creates a new mock instance.
func NewMockIdentityKnowledgeAPIClient(ctrl *gomock.Controller) *MockIdentityKnowledgeAPIClient {
	mock := &MockIdentityKnowledgeAPIClient{ctrl: ctrl}
	mock.recorder = &MockIdentityKnowledgeAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityKnowledgeAPIClient) EXPECT() *MockIdentityKnowledgeAPIClientMockRecorder {
	return m.recorder
}

// IdentityKnowledgeRead mocks base method.
func (m *MockIdentityKnowledgeAPIClient) IdentityKnowledgeRead(ctx context.Context, in *knowledgev1beta2.IdentityKnowledgeReadRequest, opts ...grpc.CallOption) (*knowledgev1beta2.IdentityKnowledgeReadResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityKnowledgeRead", varargs...)
	ret0, _ := ret[0].(*knowledgev1beta2.IdentityKnowledgeReadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityKnowledgeRead indicates an expected call of IdentityKnowledgeRead.
func (mr *MockIdentityKnowledgeAPIClientMockRecorder) IdentityKnowledgeRead(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityKnowledgeRead", reflect.TypeOf((*MockIdentityKnowledgeAPIClient)(nil).IdentityKnowledgeRead), varargs...)
}
