// Copyright (c) 2022 IndyKite
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: ./gen/indykite/identity/v1beta2/identity_management_api_grpc.pb.go

// Package identity is a generated GoMock package.
package identity

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"

	identityv1beta2 "github.com/indykite/indykite-sdk-go/gen/indykite/identity/v1beta2"
)

// MockIdentityManagementAPIClient is a mock of IdentityManagementAPIClient interface.
type MockIdentityManagementAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityManagementAPIClientMockRecorder
}

// MockIdentityManagementAPIClientMockRecorder is the mock recorder for MockIdentityManagementAPIClient.
type MockIdentityManagementAPIClientMockRecorder struct {
	mock *MockIdentityManagementAPIClient
}

// NewMockIdentityManagementAPIClient creates a new mock instance.
func NewMockIdentityManagementAPIClient(ctrl *gomock.Controller) *MockIdentityManagementAPIClient {
	mock := &MockIdentityManagementAPIClient{ctrl: ctrl}
	mock.recorder = &MockIdentityManagementAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityManagementAPIClient) EXPECT() *MockIdentityManagementAPIClientMockRecorder {
	return m.recorder
}

// CancelInvitation mocks base method.
func (m *MockIdentityManagementAPIClient) CancelInvitation(ctx context.Context, in *identityv1beta2.CancelInvitationRequest, opts ...grpc.CallOption) (*identityv1beta2.CancelInvitationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelInvitation", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CancelInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelInvitation indicates an expected call of CancelInvitation.
func (mr *MockIdentityManagementAPIClientMockRecorder) CancelInvitation(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvitation", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CancelInvitation), varargs...)
}

// ChangePassword mocks base method.
func (m *MockIdentityManagementAPIClient) ChangePassword(ctx context.Context, in *identityv1beta2.ChangePasswordRequest, opts ...grpc.CallOption) (*identityv1beta2.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockIdentityManagementAPIClientMockRecorder) ChangePassword(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).ChangePassword), varargs...)
}

// CheckInvitationState mocks base method.
func (m *MockIdentityManagementAPIClient) CheckInvitationState(ctx context.Context, in *identityv1beta2.CheckInvitationStateRequest, opts ...grpc.CallOption) (*identityv1beta2.CheckInvitationStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckInvitationState", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CheckInvitationStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvitationState indicates an expected call of CheckInvitationState.
func (mr *MockIdentityManagementAPIClientMockRecorder) CheckInvitationState(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvitationState", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CheckInvitationState), varargs...)
}

// CheckOAuth2ConsentChallenge mocks base method.
func (m *MockIdentityManagementAPIClient) CheckOAuth2ConsentChallenge(ctx context.Context, in *identityv1beta2.CheckOAuth2ConsentChallengeRequest, opts ...grpc.CallOption) (*identityv1beta2.CheckOAuth2ConsentChallengeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckOAuth2ConsentChallenge", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CheckOAuth2ConsentChallengeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOAuth2ConsentChallenge indicates an expected call of CheckOAuth2ConsentChallenge.
func (mr *MockIdentityManagementAPIClientMockRecorder) CheckOAuth2ConsentChallenge(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOAuth2ConsentChallenge", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CheckOAuth2ConsentChallenge), varargs...)
}

// CreateConsent mocks base method.
func (m *MockIdentityManagementAPIClient) CreateConsent(ctx context.Context, in *identityv1beta2.CreateConsentRequest, opts ...grpc.CallOption) (*identityv1beta2.CreateConsentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateConsent", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CreateConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsent indicates an expected call of CreateConsent.
func (mr *MockIdentityManagementAPIClientMockRecorder) CreateConsent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsent", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CreateConsent), varargs...)
}

// CreateCustomLoginToken mocks base method.
func (m *MockIdentityManagementAPIClient) CreateCustomLoginToken(ctx context.Context, in *identityv1beta2.CreateCustomLoginTokenRequest, opts ...grpc.CallOption) (*identityv1beta2.CreateCustomLoginTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCustomLoginToken", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CreateCustomLoginTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomLoginToken indicates an expected call of CreateCustomLoginToken.
func (mr *MockIdentityManagementAPIClientMockRecorder) CreateCustomLoginToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomLoginToken", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CreateCustomLoginToken), varargs...)
}

// CreateInvitation mocks base method.
func (m *MockIdentityManagementAPIClient) CreateInvitation(ctx context.Context, in *identityv1beta2.CreateInvitationRequest, opts ...grpc.CallOption) (*identityv1beta2.CreateInvitationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInvitation", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CreateInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockIdentityManagementAPIClientMockRecorder) CreateInvitation(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CreateInvitation), varargs...)
}

// CreateOAuth2ConsentVerifier mocks base method.
func (m *MockIdentityManagementAPIClient) CreateOAuth2ConsentVerifier(ctx context.Context, in *identityv1beta2.CreateOAuth2ConsentVerifierRequest, opts ...grpc.CallOption) (*identityv1beta2.CreateOAuth2ConsentVerifierResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOAuth2ConsentVerifier", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.CreateOAuth2ConsentVerifierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOAuth2ConsentVerifier indicates an expected call of CreateOAuth2ConsentVerifier.
func (mr *MockIdentityManagementAPIClientMockRecorder) CreateOAuth2ConsentVerifier(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuth2ConsentVerifier", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).CreateOAuth2ConsentVerifier), varargs...)
}

// DeleteDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIClient) DeleteDigitalTwin(ctx context.Context, in *identityv1beta2.DeleteDigitalTwinRequest, opts ...grpc.CallOption) (*identityv1beta2.DeleteDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDigitalTwin", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.DeleteDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDigitalTwin indicates an expected call of DeleteDigitalTwin.
func (mr *MockIdentityManagementAPIClientMockRecorder) DeleteDigitalTwin(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).DeleteDigitalTwin), varargs...)
}

// EnrichToken mocks base method.
func (m *MockIdentityManagementAPIClient) EnrichToken(ctx context.Context, in *identityv1beta2.EnrichTokenRequest, opts ...grpc.CallOption) (*identityv1beta2.EnrichTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnrichToken", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.EnrichTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnrichToken indicates an expected call of EnrichToken.
func (mr *MockIdentityManagementAPIClientMockRecorder) EnrichToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichToken", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).EnrichToken), varargs...)
}

// GetAccessToken mocks base method.
func (m *MockIdentityManagementAPIClient) GetAccessToken(ctx context.Context, in *identityv1beta2.GetAccessTokenRequest, opts ...grpc.CallOption) (*identityv1beta2.GetAccessTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccessToken", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.GetAccessTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockIdentityManagementAPIClientMockRecorder) GetAccessToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).GetAccessToken), varargs...)
}

// GetDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIClient) GetDigitalTwin(ctx context.Context, in *identityv1beta2.GetDigitalTwinRequest, opts ...grpc.CallOption) (*identityv1beta2.GetDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDigitalTwin", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.GetDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDigitalTwin indicates an expected call of GetDigitalTwin.
func (mr *MockIdentityManagementAPIClientMockRecorder) GetDigitalTwin(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).GetDigitalTwin), varargs...)
}

// GetPasswordCredential mocks base method.
func (m *MockIdentityManagementAPIClient) GetPasswordCredential(ctx context.Context, in *identityv1beta2.GetPasswordCredentialRequest, opts ...grpc.CallOption) (*identityv1beta2.GetPasswordCredentialResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPasswordCredential", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.GetPasswordCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordCredential indicates an expected call of GetPasswordCredential.
func (mr *MockIdentityManagementAPIClientMockRecorder) GetPasswordCredential(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordCredential", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).GetPasswordCredential), varargs...)
}

// ImportDigitalTwins mocks base method.
func (m *MockIdentityManagementAPIClient) ImportDigitalTwins(ctx context.Context, in *identityv1beta2.ImportDigitalTwinsRequest, opts ...grpc.CallOption) (*identityv1beta2.ImportDigitalTwinsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ImportDigitalTwins", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.ImportDigitalTwinsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportDigitalTwins indicates an expected call of ImportDigitalTwins.
func (mr *MockIdentityManagementAPIClientMockRecorder) ImportDigitalTwins(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportDigitalTwins", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).ImportDigitalTwins), varargs...)
}

// ListConsents mocks base method.
func (m *MockIdentityManagementAPIClient) ListConsents(ctx context.Context, in *identityv1beta2.ListConsentsRequest, opts ...grpc.CallOption) (identityv1beta2.IdentityManagementAPI_ListConsentsClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConsents", varargs...)
	ret0, _ := ret[0].(identityv1beta2.IdentityManagementAPI_ListConsentsClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsents indicates an expected call of ListConsents.
func (mr *MockIdentityManagementAPIClientMockRecorder) ListConsents(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsents", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).ListConsents), varargs...)
}

// ListDigitalTwins mocks base method.
func (m *MockIdentityManagementAPIClient) ListDigitalTwins(ctx context.Context, in *identityv1beta2.ListDigitalTwinsRequest, opts ...grpc.CallOption) (*identityv1beta2.ListDigitalTwinsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDigitalTwins", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.ListDigitalTwinsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDigitalTwins indicates an expected call of ListDigitalTwins.
func (mr *MockIdentityManagementAPIClientMockRecorder) ListDigitalTwins(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDigitalTwins", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).ListDigitalTwins), varargs...)
}

// PatchDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIClient) PatchDigitalTwin(ctx context.Context, in *identityv1beta2.PatchDigitalTwinRequest, opts ...grpc.CallOption) (*identityv1beta2.PatchDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PatchDigitalTwin", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.PatchDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchDigitalTwin indicates an expected call of PatchDigitalTwin.
func (mr *MockIdentityManagementAPIClientMockRecorder) PatchDigitalTwin(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).PatchDigitalTwin), varargs...)
}

// RegisterDigitalTwinWithoutCredential mocks base method.
func (m *MockIdentityManagementAPIClient) RegisterDigitalTwinWithoutCredential(ctx context.Context, in *identityv1beta2.RegisterDigitalTwinWithoutCredentialRequest, opts ...grpc.CallOption) (*identityv1beta2.RegisterDigitalTwinWithoutCredentialResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterDigitalTwinWithoutCredential", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.RegisterDigitalTwinWithoutCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDigitalTwinWithoutCredential indicates an expected call of RegisterDigitalTwinWithoutCredential.
func (mr *MockIdentityManagementAPIClientMockRecorder) RegisterDigitalTwinWithoutCredential(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDigitalTwinWithoutCredential", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).RegisterDigitalTwinWithoutCredential), varargs...)
}

// ResendInvitation mocks base method.
func (m *MockIdentityManagementAPIClient) ResendInvitation(ctx context.Context, in *identityv1beta2.ResendInvitationRequest, opts ...grpc.CallOption) (*identityv1beta2.ResendInvitationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ResendInvitation", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.ResendInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendInvitation indicates an expected call of ResendInvitation.
func (mr *MockIdentityManagementAPIClientMockRecorder) ResendInvitation(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendInvitation", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).ResendInvitation), varargs...)
}

// RevokeConsent mocks base method.
func (m *MockIdentityManagementAPIClient) RevokeConsent(ctx context.Context, in *identityv1beta2.RevokeConsentRequest, opts ...grpc.CallOption) (*identityv1beta2.RevokeConsentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeConsent", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.RevokeConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeConsent indicates an expected call of RevokeConsent.
func (mr *MockIdentityManagementAPIClientMockRecorder) RevokeConsent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeConsent", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).RevokeConsent), varargs...)
}

// SelfServiceTerminateSession mocks base method.
func (m *MockIdentityManagementAPIClient) SelfServiceTerminateSession(ctx context.Context, in *identityv1beta2.SelfServiceTerminateSessionRequest, opts ...grpc.CallOption) (*identityv1beta2.SelfServiceTerminateSessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SelfServiceTerminateSession", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.SelfServiceTerminateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfServiceTerminateSession indicates an expected call of SelfServiceTerminateSession.
func (mr *MockIdentityManagementAPIClientMockRecorder) SelfServiceTerminateSession(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfServiceTerminateSession", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).SelfServiceTerminateSession), varargs...)
}

// SessionIntrospect mocks base method.
func (m *MockIdentityManagementAPIClient) SessionIntrospect(ctx context.Context, in *identityv1beta2.SessionIntrospectRequest, opts ...grpc.CallOption) (*identityv1beta2.SessionIntrospectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SessionIntrospect", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.SessionIntrospectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionIntrospect indicates an expected call of SessionIntrospect.
func (mr *MockIdentityManagementAPIClientMockRecorder) SessionIntrospect(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionIntrospect", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).SessionIntrospect), varargs...)
}

// StartDigitalTwinEmailVerification mocks base method.
func (m *MockIdentityManagementAPIClient) StartDigitalTwinEmailVerification(ctx context.Context, in *identityv1beta2.StartDigitalTwinEmailVerificationRequest, opts ...grpc.CallOption) (*identityv1beta2.StartDigitalTwinEmailVerificationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartDigitalTwinEmailVerification", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.StartDigitalTwinEmailVerificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDigitalTwinEmailVerification indicates an expected call of StartDigitalTwinEmailVerification.
func (mr *MockIdentityManagementAPIClientMockRecorder) StartDigitalTwinEmailVerification(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDigitalTwinEmailVerification", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).StartDigitalTwinEmailVerification), varargs...)
}

// StartForgottenPasswordFlow mocks base method.
func (m *MockIdentityManagementAPIClient) StartForgottenPasswordFlow(ctx context.Context, in *identityv1beta2.StartForgottenPasswordFlowRequest, opts ...grpc.CallOption) (*identityv1beta2.StartForgottenPasswordFlowResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartForgottenPasswordFlow", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.StartForgottenPasswordFlowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartForgottenPasswordFlow indicates an expected call of StartForgottenPasswordFlow.
func (mr *MockIdentityManagementAPIClientMockRecorder) StartForgottenPasswordFlow(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartForgottenPasswordFlow", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).StartForgottenPasswordFlow), varargs...)
}

// TokenIntrospect mocks base method.
func (m *MockIdentityManagementAPIClient) TokenIntrospect(ctx context.Context, in *identityv1beta2.TokenIntrospectRequest, opts ...grpc.CallOption) (*identityv1beta2.TokenIntrospectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TokenIntrospect", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.TokenIntrospectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenIntrospect indicates an expected call of TokenIntrospect.
func (mr *MockIdentityManagementAPIClientMockRecorder) TokenIntrospect(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenIntrospect", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).TokenIntrospect), varargs...)
}

// UpdatePasswordCredential mocks base method.
func (m *MockIdentityManagementAPIClient) UpdatePasswordCredential(ctx context.Context, in *identityv1beta2.UpdatePasswordCredentialRequest, opts ...grpc.CallOption) (*identityv1beta2.UpdatePasswordCredentialResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePasswordCredential", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.UpdatePasswordCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordCredential indicates an expected call of UpdatePasswordCredential.
func (mr *MockIdentityManagementAPIClientMockRecorder) UpdatePasswordCredential(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordCredential", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).UpdatePasswordCredential), varargs...)
}

// VerifyDigitalTwinEmail mocks base method.
func (m *MockIdentityManagementAPIClient) VerifyDigitalTwinEmail(ctx context.Context, in *identityv1beta2.VerifyDigitalTwinEmailRequest, opts ...grpc.CallOption) (*identityv1beta2.VerifyDigitalTwinEmailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyDigitalTwinEmail", varargs...)
	ret0, _ := ret[0].(*identityv1beta2.VerifyDigitalTwinEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDigitalTwinEmail indicates an expected call of VerifyDigitalTwinEmail.
func (mr *MockIdentityManagementAPIClientMockRecorder) VerifyDigitalTwinEmail(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDigitalTwinEmail", reflect.TypeOf((*MockIdentityManagementAPIClient)(nil).VerifyDigitalTwinEmail), varargs...)
}

// MockIdentityManagementAPI_ListConsentsClient is a mock of IdentityManagementAPI_ListConsentsClient interface.
type MockIdentityManagementAPI_ListConsentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityManagementAPI_ListConsentsClientMockRecorder
}

// MockIdentityManagementAPI_ListConsentsClientMockRecorder is the mock recorder for MockIdentityManagementAPI_ListConsentsClient.
type MockIdentityManagementAPI_ListConsentsClientMockRecorder struct {
	mock *MockIdentityManagementAPI_ListConsentsClient
}

// NewMockIdentityManagementAPI_ListConsentsClient creates a new mock instance.
func NewMockIdentityManagementAPI_ListConsentsClient(ctrl *gomock.Controller) *MockIdentityManagementAPI_ListConsentsClient {
	mock := &MockIdentityManagementAPI_ListConsentsClient{ctrl: ctrl}
	mock.recorder = &MockIdentityManagementAPI_ListConsentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityManagementAPI_ListConsentsClient) EXPECT() *MockIdentityManagementAPI_ListConsentsClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).Context))
}

// Header mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsClient) Recv() (*identityv1beta2.ListConsentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*identityv1beta2.ListConsentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockIdentityManagementAPI_ListConsentsClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockIdentityManagementAPI_ListConsentsClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockIdentityManagementAPI_ListConsentsClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsClient)(nil).Trailer))
}

// MockIdentityManagementAPIServer is a mock of IdentityManagementAPIServer interface.
type MockIdentityManagementAPIServer struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityManagementAPIServerMockRecorder
}

// MockIdentityManagementAPIServerMockRecorder is the mock recorder for MockIdentityManagementAPIServer.
type MockIdentityManagementAPIServerMockRecorder struct {
	mock *MockIdentityManagementAPIServer
}

// NewMockIdentityManagementAPIServer creates a new mock instance.
func NewMockIdentityManagementAPIServer(ctrl *gomock.Controller) *MockIdentityManagementAPIServer {
	mock := &MockIdentityManagementAPIServer{ctrl: ctrl}
	mock.recorder = &MockIdentityManagementAPIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityManagementAPIServer) EXPECT() *MockIdentityManagementAPIServerMockRecorder {
	return m.recorder
}

// CancelInvitation mocks base method.
func (m *MockIdentityManagementAPIServer) CancelInvitation(arg0 context.Context, arg1 *identityv1beta2.CancelInvitationRequest) (*identityv1beta2.CancelInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelInvitation", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CancelInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelInvitation indicates an expected call of CancelInvitation.
func (mr *MockIdentityManagementAPIServerMockRecorder) CancelInvitation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelInvitation", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CancelInvitation), arg0, arg1)
}

// ChangePassword mocks base method.
func (m *MockIdentityManagementAPIServer) ChangePassword(arg0 context.Context, arg1 *identityv1beta2.ChangePasswordRequest) (*identityv1beta2.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockIdentityManagementAPIServerMockRecorder) ChangePassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).ChangePassword), arg0, arg1)
}

// CheckInvitationState mocks base method.
func (m *MockIdentityManagementAPIServer) CheckInvitationState(arg0 context.Context, arg1 *identityv1beta2.CheckInvitationStateRequest) (*identityv1beta2.CheckInvitationStateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvitationState", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CheckInvitationStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvitationState indicates an expected call of CheckInvitationState.
func (mr *MockIdentityManagementAPIServerMockRecorder) CheckInvitationState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvitationState", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CheckInvitationState), arg0, arg1)
}

// CheckOAuth2ConsentChallenge mocks base method.
func (m *MockIdentityManagementAPIServer) CheckOAuth2ConsentChallenge(arg0 context.Context, arg1 *identityv1beta2.CheckOAuth2ConsentChallengeRequest) (*identityv1beta2.CheckOAuth2ConsentChallengeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOAuth2ConsentChallenge", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CheckOAuth2ConsentChallengeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOAuth2ConsentChallenge indicates an expected call of CheckOAuth2ConsentChallenge.
func (mr *MockIdentityManagementAPIServerMockRecorder) CheckOAuth2ConsentChallenge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOAuth2ConsentChallenge", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CheckOAuth2ConsentChallenge), arg0, arg1)
}

// CreateConsent mocks base method.
func (m *MockIdentityManagementAPIServer) CreateConsent(arg0 context.Context, arg1 *identityv1beta2.CreateConsentRequest) (*identityv1beta2.CreateConsentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsent", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CreateConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsent indicates an expected call of CreateConsent.
func (mr *MockIdentityManagementAPIServerMockRecorder) CreateConsent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsent", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CreateConsent), arg0, arg1)
}

// CreateCustomLoginToken mocks base method.
func (m *MockIdentityManagementAPIServer) CreateCustomLoginToken(arg0 context.Context, arg1 *identityv1beta2.CreateCustomLoginTokenRequest) (*identityv1beta2.CreateCustomLoginTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomLoginToken", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CreateCustomLoginTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomLoginToken indicates an expected call of CreateCustomLoginToken.
func (mr *MockIdentityManagementAPIServerMockRecorder) CreateCustomLoginToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomLoginToken", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CreateCustomLoginToken), arg0, arg1)
}

// CreateInvitation mocks base method.
func (m *MockIdentityManagementAPIServer) CreateInvitation(arg0 context.Context, arg1 *identityv1beta2.CreateInvitationRequest) (*identityv1beta2.CreateInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CreateInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockIdentityManagementAPIServerMockRecorder) CreateInvitation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CreateInvitation), arg0, arg1)
}

// CreateOAuth2ConsentVerifier mocks base method.
func (m *MockIdentityManagementAPIServer) CreateOAuth2ConsentVerifier(arg0 context.Context, arg1 *identityv1beta2.CreateOAuth2ConsentVerifierRequest) (*identityv1beta2.CreateOAuth2ConsentVerifierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuth2ConsentVerifier", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.CreateOAuth2ConsentVerifierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOAuth2ConsentVerifier indicates an expected call of CreateOAuth2ConsentVerifier.
func (mr *MockIdentityManagementAPIServerMockRecorder) CreateOAuth2ConsentVerifier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuth2ConsentVerifier", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).CreateOAuth2ConsentVerifier), arg0, arg1)
}

// DeleteDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIServer) DeleteDigitalTwin(arg0 context.Context, arg1 *identityv1beta2.DeleteDigitalTwinRequest) (*identityv1beta2.DeleteDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDigitalTwin", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.DeleteDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDigitalTwin indicates an expected call of DeleteDigitalTwin.
func (mr *MockIdentityManagementAPIServerMockRecorder) DeleteDigitalTwin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).DeleteDigitalTwin), arg0, arg1)
}

// EnrichToken mocks base method.
func (m *MockIdentityManagementAPIServer) EnrichToken(arg0 context.Context, arg1 *identityv1beta2.EnrichTokenRequest) (*identityv1beta2.EnrichTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichToken", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.EnrichTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnrichToken indicates an expected call of EnrichToken.
func (mr *MockIdentityManagementAPIServerMockRecorder) EnrichToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichToken", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).EnrichToken), arg0, arg1)
}

// GetAccessToken mocks base method.
func (m *MockIdentityManagementAPIServer) GetAccessToken(arg0 context.Context, arg1 *identityv1beta2.GetAccessTokenRequest) (*identityv1beta2.GetAccessTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.GetAccessTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockIdentityManagementAPIServerMockRecorder) GetAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).GetAccessToken), arg0, arg1)
}

// GetDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIServer) GetDigitalTwin(arg0 context.Context, arg1 *identityv1beta2.GetDigitalTwinRequest) (*identityv1beta2.GetDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDigitalTwin", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.GetDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDigitalTwin indicates an expected call of GetDigitalTwin.
func (mr *MockIdentityManagementAPIServerMockRecorder) GetDigitalTwin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).GetDigitalTwin), arg0, arg1)
}

// GetPasswordCredential mocks base method.
func (m *MockIdentityManagementAPIServer) GetPasswordCredential(arg0 context.Context, arg1 *identityv1beta2.GetPasswordCredentialRequest) (*identityv1beta2.GetPasswordCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordCredential", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.GetPasswordCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordCredential indicates an expected call of GetPasswordCredential.
func (mr *MockIdentityManagementAPIServerMockRecorder) GetPasswordCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordCredential", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).GetPasswordCredential), arg0, arg1)
}

// ImportDigitalTwins mocks base method.
func (m *MockIdentityManagementAPIServer) ImportDigitalTwins(arg0 context.Context, arg1 *identityv1beta2.ImportDigitalTwinsRequest) (*identityv1beta2.ImportDigitalTwinsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportDigitalTwins", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.ImportDigitalTwinsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportDigitalTwins indicates an expected call of ImportDigitalTwins.
func (mr *MockIdentityManagementAPIServerMockRecorder) ImportDigitalTwins(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportDigitalTwins", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).ImportDigitalTwins), arg0, arg1)
}

// ListConsents mocks base method.
func (m *MockIdentityManagementAPIServer) ListConsents(arg0 *identityv1beta2.ListConsentsRequest, arg1 identityv1beta2.IdentityManagementAPI_ListConsentsServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsents", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListConsents indicates an expected call of ListConsents.
func (mr *MockIdentityManagementAPIServerMockRecorder) ListConsents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsents", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).ListConsents), arg0, arg1)
}

// ListDigitalTwins mocks base method.
func (m *MockIdentityManagementAPIServer) ListDigitalTwins(arg0 context.Context, arg1 *identityv1beta2.ListDigitalTwinsRequest) (*identityv1beta2.ListDigitalTwinsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDigitalTwins", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.ListDigitalTwinsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDigitalTwins indicates an expected call of ListDigitalTwins.
func (mr *MockIdentityManagementAPIServerMockRecorder) ListDigitalTwins(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDigitalTwins", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).ListDigitalTwins), arg0, arg1)
}

// PatchDigitalTwin mocks base method.
func (m *MockIdentityManagementAPIServer) PatchDigitalTwin(arg0 context.Context, arg1 *identityv1beta2.PatchDigitalTwinRequest) (*identityv1beta2.PatchDigitalTwinResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchDigitalTwin", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.PatchDigitalTwinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchDigitalTwin indicates an expected call of PatchDigitalTwin.
func (mr *MockIdentityManagementAPIServerMockRecorder) PatchDigitalTwin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchDigitalTwin", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).PatchDigitalTwin), arg0, arg1)
}

// RegisterDigitalTwinWithoutCredential mocks base method.
func (m *MockIdentityManagementAPIServer) RegisterDigitalTwinWithoutCredential(arg0 context.Context, arg1 *identityv1beta2.RegisterDigitalTwinWithoutCredentialRequest) (*identityv1beta2.RegisterDigitalTwinWithoutCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDigitalTwinWithoutCredential", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.RegisterDigitalTwinWithoutCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDigitalTwinWithoutCredential indicates an expected call of RegisterDigitalTwinWithoutCredential.
func (mr *MockIdentityManagementAPIServerMockRecorder) RegisterDigitalTwinWithoutCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDigitalTwinWithoutCredential", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).RegisterDigitalTwinWithoutCredential), arg0, arg1)
}

// ResendInvitation mocks base method.
func (m *MockIdentityManagementAPIServer) ResendInvitation(arg0 context.Context, arg1 *identityv1beta2.ResendInvitationRequest) (*identityv1beta2.ResendInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendInvitation", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.ResendInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResendInvitation indicates an expected call of ResendInvitation.
func (mr *MockIdentityManagementAPIServerMockRecorder) ResendInvitation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendInvitation", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).ResendInvitation), arg0, arg1)
}

// RevokeConsent mocks base method.
func (m *MockIdentityManagementAPIServer) RevokeConsent(arg0 context.Context, arg1 *identityv1beta2.RevokeConsentRequest) (*identityv1beta2.RevokeConsentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeConsent", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.RevokeConsentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeConsent indicates an expected call of RevokeConsent.
func (mr *MockIdentityManagementAPIServerMockRecorder) RevokeConsent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeConsent", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).RevokeConsent), arg0, arg1)
}

// SelfServiceTerminateSession mocks base method.
func (m *MockIdentityManagementAPIServer) SelfServiceTerminateSession(arg0 context.Context, arg1 *identityv1beta2.SelfServiceTerminateSessionRequest) (*identityv1beta2.SelfServiceTerminateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelfServiceTerminateSession", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.SelfServiceTerminateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelfServiceTerminateSession indicates an expected call of SelfServiceTerminateSession.
func (mr *MockIdentityManagementAPIServerMockRecorder) SelfServiceTerminateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelfServiceTerminateSession", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).SelfServiceTerminateSession), arg0, arg1)
}

// SessionIntrospect mocks base method.
func (m *MockIdentityManagementAPIServer) SessionIntrospect(arg0 context.Context, arg1 *identityv1beta2.SessionIntrospectRequest) (*identityv1beta2.SessionIntrospectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionIntrospect", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.SessionIntrospectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionIntrospect indicates an expected call of SessionIntrospect.
func (mr *MockIdentityManagementAPIServerMockRecorder) SessionIntrospect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionIntrospect", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).SessionIntrospect), arg0, arg1)
}

// StartDigitalTwinEmailVerification mocks base method.
func (m *MockIdentityManagementAPIServer) StartDigitalTwinEmailVerification(arg0 context.Context, arg1 *identityv1beta2.StartDigitalTwinEmailVerificationRequest) (*identityv1beta2.StartDigitalTwinEmailVerificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDigitalTwinEmailVerification", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.StartDigitalTwinEmailVerificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDigitalTwinEmailVerification indicates an expected call of StartDigitalTwinEmailVerification.
func (mr *MockIdentityManagementAPIServerMockRecorder) StartDigitalTwinEmailVerification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDigitalTwinEmailVerification", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).StartDigitalTwinEmailVerification), arg0, arg1)
}

// StartForgottenPasswordFlow mocks base method.
func (m *MockIdentityManagementAPIServer) StartForgottenPasswordFlow(arg0 context.Context, arg1 *identityv1beta2.StartForgottenPasswordFlowRequest) (*identityv1beta2.StartForgottenPasswordFlowResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartForgottenPasswordFlow", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.StartForgottenPasswordFlowResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartForgottenPasswordFlow indicates an expected call of StartForgottenPasswordFlow.
func (mr *MockIdentityManagementAPIServerMockRecorder) StartForgottenPasswordFlow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartForgottenPasswordFlow", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).StartForgottenPasswordFlow), arg0, arg1)
}

// TokenIntrospect mocks base method.
func (m *MockIdentityManagementAPIServer) TokenIntrospect(arg0 context.Context, arg1 *identityv1beta2.TokenIntrospectRequest) (*identityv1beta2.TokenIntrospectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenIntrospect", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.TokenIntrospectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenIntrospect indicates an expected call of TokenIntrospect.
func (mr *MockIdentityManagementAPIServerMockRecorder) TokenIntrospect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenIntrospect", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).TokenIntrospect), arg0, arg1)
}

// UpdatePasswordCredential mocks base method.
func (m *MockIdentityManagementAPIServer) UpdatePasswordCredential(arg0 context.Context, arg1 *identityv1beta2.UpdatePasswordCredentialRequest) (*identityv1beta2.UpdatePasswordCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordCredential", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.UpdatePasswordCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordCredential indicates an expected call of UpdatePasswordCredential.
func (mr *MockIdentityManagementAPIServerMockRecorder) UpdatePasswordCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordCredential", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).UpdatePasswordCredential), arg0, arg1)
}

// VerifyDigitalTwinEmail mocks base method.
func (m *MockIdentityManagementAPIServer) VerifyDigitalTwinEmail(arg0 context.Context, arg1 *identityv1beta2.VerifyDigitalTwinEmailRequest) (*identityv1beta2.VerifyDigitalTwinEmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDigitalTwinEmail", arg0, arg1)
	ret0, _ := ret[0].(*identityv1beta2.VerifyDigitalTwinEmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDigitalTwinEmail indicates an expected call of VerifyDigitalTwinEmail.
func (mr *MockIdentityManagementAPIServerMockRecorder) VerifyDigitalTwinEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDigitalTwinEmail", reflect.TypeOf((*MockIdentityManagementAPIServer)(nil).VerifyDigitalTwinEmail), arg0, arg1)
}

// MockUnsafeIdentityManagementAPIServer is a mock of UnsafeIdentityManagementAPIServer interface.
type MockUnsafeIdentityManagementAPIServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeIdentityManagementAPIServerMockRecorder
}

// MockUnsafeIdentityManagementAPIServerMockRecorder is the mock recorder for MockUnsafeIdentityManagementAPIServer.
type MockUnsafeIdentityManagementAPIServerMockRecorder struct {
	mock *MockUnsafeIdentityManagementAPIServer
}

// NewMockUnsafeIdentityManagementAPIServer creates a new mock instance.
func NewMockUnsafeIdentityManagementAPIServer(ctrl *gomock.Controller) *MockUnsafeIdentityManagementAPIServer {
	mock := &MockUnsafeIdentityManagementAPIServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeIdentityManagementAPIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeIdentityManagementAPIServer) EXPECT() *MockUnsafeIdentityManagementAPIServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedIdentityManagementAPIServer mocks base method.
func (m *MockUnsafeIdentityManagementAPIServer) mustEmbedUnimplementedIdentityManagementAPIServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIdentityManagementAPIServer")
}

// mustEmbedUnimplementedIdentityManagementAPIServer indicates an expected call of mustEmbedUnimplementedIdentityManagementAPIServer.
func (mr *MockUnsafeIdentityManagementAPIServerMockRecorder) mustEmbedUnimplementedIdentityManagementAPIServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIdentityManagementAPIServer", reflect.TypeOf((*MockUnsafeIdentityManagementAPIServer)(nil).mustEmbedUnimplementedIdentityManagementAPIServer))
}

// MockIdentityManagementAPI_ListConsentsServer is a mock of IdentityManagementAPI_ListConsentsServer interface.
type MockIdentityManagementAPI_ListConsentsServer struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityManagementAPI_ListConsentsServerMockRecorder
}

// MockIdentityManagementAPI_ListConsentsServerMockRecorder is the mock recorder for MockIdentityManagementAPI_ListConsentsServer.
type MockIdentityManagementAPI_ListConsentsServerMockRecorder struct {
	mock *MockIdentityManagementAPI_ListConsentsServer
}

// NewMockIdentityManagementAPI_ListConsentsServer creates a new mock instance.
func NewMockIdentityManagementAPI_ListConsentsServer(ctrl *gomock.Controller) *MockIdentityManagementAPI_ListConsentsServer {
	mock := &MockIdentityManagementAPI_ListConsentsServer{ctrl: ctrl}
	mock.recorder = &MockIdentityManagementAPI_ListConsentsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityManagementAPI_ListConsentsServer) EXPECT() *MockIdentityManagementAPI_ListConsentsServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockIdentityManagementAPI_ListConsentsServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsServer) Send(arg0 *identityv1beta2.ListConsentsResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockIdentityManagementAPI_ListConsentsServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockIdentityManagementAPI_ListConsentsServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockIdentityManagementAPI_ListConsentsServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockIdentityManagementAPI_ListConsentsServer)(nil).SetTrailer), arg0)
}
