---
name: Release notes
on: # yamllint disable-line rule:truthy
  push:
    branches: ["dev", "develop", "main", "master"]

# https://github.com/googleapis/release-please-action?tab=readme-ov-file#workflow-permissions
permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency: release-notes

jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
    steps:
      - name: action/release-please
        uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0 - https://github.com/googleapis/release-please-action/releases
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: actions/slack-notification
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1 - https://github.com/slackapi/slack-github-action/releases
        if: ${{ steps.release.outputs.release_created }}
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: >-
            {
              "channel": "${{ vars.SLACK_CHANNEL_IK_SDK }}",
              "text": "`indykite-sdk-go` release ${{ format('v{0}', steps.release.outputs.version) }} is ready:
                format('<{0}/{1}/pull/{2}|{1]#{2]}}>', github.server_url, github.repository, steps.release.outputs.pr.number)"
            }
